// src/pdm/pdm_capture.c — PIO + FREE-RUNNING DMA raw PDM ring -> 4 CICs -> PCM.
// Bit layout per 32-bit ISR word (shift-left, MSB-first): groups of 4 bits
// [sig2_hi, sig1_hi, sig2_lo, sig1_lo] x 8, oldest in the high bits.
// IN_BASE is SIG1 (GPIO29), which is the LSB of each `in pins, 2` sample.
//
// The DMA writes raw PIO words into a power-of-two ring CONTINUOUSLY (address
// wrap, count ~= infinite), so capture never stops and has no per-block gap or
// warmup discard. A single consumer (pdm_capture_pull, on the real-time audio
// core) decimates everything between its read cursor and the DMA's live write
// cursor. This is what makes glitch-free continuous beam audio possible.
#include "pdm/pdm_capture.h"
#include "dsp/cic.h"
#include "platform/board.h"
#include "platform/ioexp.h"
#include "platform/diag.h"
#include "pdm_capture.pio.h"          // generated by pico_generate_pio_header
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "pico/stdlib.h"

// Raw ring: 8192 32-bit words = 32 KiB. Each word = 8 PDM periods; CIC_DECIMATE
// (64) bits -> 1 PCM sample => 8 words per PCM sample per mic, so the ring holds
// 1024 PCM samples (~64 ms @ 16 kHz) of slack before the consumer must catch up.
// MUST be aligned to its byte size for the DMA write-address ring wrap.
#define RAW_WORDS     8192u
#define RAW_RING_BITS 15u             // log2(RAW_WORDS * 4 bytes)
static uint32_t s_raw[RAW_WORDS] __attribute__((aligned(RAW_WORDS * 4)));

static PIO  s_pio = pio1;   // ADAPTATION: microphonearray used pio0; wilibsp
                            // reserves pio0=audio, pio2=radio (re-based to GPIO
                            // 16). pio1 (LEDs) has room: 4+4 instructions, and
                            // GPIO 28-30 are inside its default pin window.
static uint s_sm, s_off, s_dma;
static cic_t s_cic[PDM_NUM_MICS];
static unsigned s_rd;                  // consumer read cursor (word index 0..RAW_WORDS-1)

void pdm_capture_init(void) {
    // ADAPTATION: the source app powered the mics in main(); the BSP driver is
    // self-contained (same normalization as spi_bus_init moving into board_init).
    // Precondition: ioexp_init() has run (board_init() does this).
    ioexp_mic_pwr(true);
    sleep_ms(50);                      // MEMS mic power-on settle

    for (int i = 0; i < PDM_NUM_MICS; i++) cic_init(&s_cic[i]);
    s_sm  = pio_claim_unused_sm(s_pio, true);
    s_off = pio_add_program(s_pio, &pdm_capture_program);
    pdm_capture_program_init(s_pio, s_sm, s_off, PIN_MIC_CLK, PIN_MIC_SIG1);

    s_dma = dma_claim_unused_channel(true);
    dma_channel_config c = dma_channel_get_default_config(s_dma);
    channel_config_set_read_increment(&c, false);          // PIO RX FIFO (fixed)
    channel_config_set_write_increment(&c, true);
    channel_config_set_ring(&c, true, RAW_RING_BITS);       // wrap WRITE addr in the ring
    channel_config_set_dreq(&c, pio_get_dreq(s_pio, s_sm, false));
    channel_config_set_transfer_data_size(&c, DMA_SIZE_32);
    // count = 0xFFFFFFFF: with the write-address ring wrap this runs ~9 hours
    // before the count expires (well beyond any session); the ring wrap keeps
    // every write inside s_raw.
    dma_channel_configure(s_dma, &c, s_raw, &s_pio->rxf[s_sm], 0xFFFFFFFFu, true);
    s_rd = 0;
    DIAG("pdm: init pio1 sm=%u dma=%u (4 mics, %u Hz PCM)\n",
         (unsigned)s_sm, (unsigned)s_dma, (unsigned)(PDM_CLK_HZ / CIC_DECIMATE));
}

// Decode one raw word: push its 32 bits to the 4 CICs in line/phase order,
// storing any decimated PCM into out[ch][idx[ch]] up to cap.
static void feed_word(uint32_t w, int16_t* out[PDM_NUM_MICS], unsigned* idx,
                      unsigned cap) {
    for (int g = 0; g < 8; g++) {
        int s1h = (w >> 30) & 1; int s2h = (w >> 31) & 1;   // SIG1=IN_BASE=LSB of each pair
        int s1l = (w >> 28) & 1; int s2l = (w >> 29) & 1;
        w <<= 4;
        int16_t pcm;
        if (cic_push_bit(&s_cic[MIC_A], s1h, &pcm) && idx[MIC_A] < cap) out[MIC_A][idx[MIC_A]++] = pcm;
        if (cic_push_bit(&s_cic[MIC_C], s2h, &pcm) && idx[MIC_C] < cap) out[MIC_C][idx[MIC_C]++] = pcm;
        if (cic_push_bit(&s_cic[MIC_B], s1l, &pcm) && idx[MIC_B] < cap) out[MIC_B][idx[MIC_B]++] = pcm;
        if (cic_push_bit(&s_cic[MIC_D], s2l, &pcm) && idx[MIC_D] < cap) out[MIC_D][idx[MIC_D]++] = pcm;
    }
}

unsigned pdm_capture_pull(int16_t* out[PDM_NUM_MICS], unsigned max) {
    unsigned idx[PDM_NUM_MICS] = {0,0,0,0};
    const uintptr_t base = (uintptr_t)s_raw;
    // Live DMA write cursor (word index within the ring).
    unsigned wr = (unsigned)(((uintptr_t)dma_hw->ch[s_dma].write_addr - base) / 4u);
    while (idx[MIC_A] < max) {
        if (s_rd == wr) {                       // caught up to the DMA — re-sample once
            wr = (unsigned)(((uintptr_t)dma_hw->ch[s_dma].write_addr - base) / 4u);
            if (s_rd == wr) break;              // truly nothing new available
        }
        uint32_t word = s_raw[s_rd];
        s_rd = (s_rd + 1u) & (RAW_WORDS - 1u);
        feed_word(word, out, idx, max);
    }
    return idx[MIC_A];
}

unsigned pdm_capture_block(int16_t* out[PDM_NUM_MICS], unsigned frames) {
    // Blocking convenience wrapper: spin on pull() until `frames` are collected.
    unsigned got = 0;
    while (got < frames) {
        int16_t* dst[PDM_NUM_MICS];
        for (int m = 0; m < PDM_NUM_MICS; m++) dst[m] = out[m] + got;
        got += pdm_capture_pull(dst, frames - got);
    }
    return got;
}
