// bsp/display/hstx_dvi.c — 640x480p60 DVI scanout over the RP2350 HSTX block.
//
// Harvested from ../movieplayer/src/display/hstx_dvi.c (stage6-hstx-dvi) with the
// HDMI-audio-island path stripped out — this is the plain-DVI scanout only. Proven
// facts baked in (see the movie player's memory freewili-hstx-dvi):
//
//   - ZERO-IRQ baked-command DMA: one SCREEN channel streams a command buffer
//     (sync RAW words + TMDS_REPEAT borders + a TMDS run of video pixels, per
//     scanline) to the HSTX FIFO; a LOOPER channel rewrites SCREEN.read_addr and
//     chains back. No interrupts. Channels are claimed dynamically.
//   - Framebuffer in SRAM. PSRAM scanout underruns the FIFO (no signal) and
//     monopolises the QMI (wedges flash). The <=480x320 video region is stored;
//     the 640x480 border is GENERATED by HSTX_CMD_TMDS_REPEAT (one word -> N
//     pixels, ~zero bandwidth), not stored.
//   - FreeWili 2 differential polarity (the colour fix): each pair's _P pin (the
//     ODD gpio 13/15/17/19 -> HSTX odd bit) is NON-inverted; the _N pin (even
//     gpio) is INVERTED.
//   - RGB565 encode == MichaelBell/dvhstx MODE_RGB565: expand_tmds L2 nbits4 rot8
//     (Red) / L1 nbits5 rot3 (Green) / L0 nbits4 rot29 (Blue); expand_shift
//     2/16/1/0. Pixels are native little-endian uint16 (NO byte-swap).
//   - clk_hstx = clk_sys/2 (read at runtime); CSR CLKDIV 5 -> pixel = clk_hstx/5.
//     clk_sys = 252 MHz -> clk_hstx 126 MHz -> 25.2 MHz pixel = standard 640x480p60
//     (DVI apps opt into 252 via board_init_clk; the board default is 250 -> 25.0).

#include "display/hstx_dvi.h"
#include "display/hstx_modes.h"

#include "pico/stdlib.h"
#include "hardware/dma.h"
#include "hardware/gpio.h"
#include "hardware/clocks.h"
#include "hardware/structs/hstx_ctrl.h"
#include "hardware/structs/hstx_fifo.h"

#define BORDER_RGB565 0x0000u   // black border around the video region

// ---------------------------------------------------------------------------
// Command-buffer sizing (plain DVI). Per video line: 6 sync dwords + 2 (left
// border) + 1 (TMDS cmd) + vid_w/2 pixel dwords + 2 (right border) = 11 + vid_w/2.
// Border-only active lines are 8 dwords. Plus ~200 dwords of vblank + margin.
// At 480x320: 200 + 320*(11+240) + 160*8 = ~81800 dwords ~= 327 KB SRAM.
#define HSTX_PLAIN_DWORDS \
    (200 + HSTX_VID_H_MAX * (11 + HSTX_VID_W_MAX / 2) + \
     (MODE_V_ACTIVE_LINES - HSTX_VID_H_MAX) * 8)

// SRAM command buffer (commands + video pixels interleaved) and scanout state.
static uint32_t framebuf[HSTX_PLAIN_DWORDS];
static uint32_t *g_loop_src = framebuf;   // LOOPER copies this into SCREEN.read_addr

static unsigned g_fill;                    // command-buffer length in dwords
static uint16_t *g_region_base;            // pixel(0,0) of the FIXED region
static uint16_t *g_video_base;             // top-left of the centered movie in it
static int g_video_stride;                 // uint16 elements per video row
static int g_region_h = HSTX_VID_H_MAX;    // stored region height
static int g_movie_w, g_movie_h;           // current movie size (<= the region)

static int ch_screen = -1, ch_looper = -1;

// One blanking band (front porch / sync / back porch worth of identical lines),
// merging each line's back-porch+active+next-front-porch into one RAW_REPEAT.
static void emit_vblank_band(unsigned *fillp, unsigned von, unsigned lines) {
    unsigned fill = *fillp;
    framebuf[fill++] = HSTX_CMD_RAW_REPEAT | MODE_H_FRONT_PORCH;
    framebuf[fill++] = von ? SYNC_V0_H1 : SYNC_V1_H1;
    for (unsigned y = 0; y < lines; y++) {
        framebuf[fill++] = HSTX_CMD_RAW_REPEAT | MODE_H_SYNC_WIDTH;
        framebuf[fill++] = von ? SYNC_V0_H0 : SYNC_V1_H0;
        framebuf[fill++] = HSTX_CMD_RAW_REPEAT |
            (MODE_H_BACK_PORCH + MODE_H_ACTIVE_PIXELS + MODE_H_FRONT_PORCH);
        framebuf[fill++] = von ? SYNC_V0_H1 : SYNC_V1_H1;
    }
    framebuf[fill - 2] = HSTX_CMD_RAW_REPEAT | (MODE_H_BACK_PORCH + MODE_H_ACTIVE_PIXELS);
    *fillp = fill;
}

// Build the whole-frame command buffer ONCE for the FIXED HSTX_VID_W_MAX x
// HSTX_VID_H_MAX video region centered in 640x480, clearing it to black. The
// movie is recentered within the region by hstx_dvi_set_geometry without touching
// the DMA.
static void hstx_build(int vid_w, int vid_h) {
    if (vid_w > HSTX_VID_W_MAX) vid_w = HSTX_VID_W_MAX;
    if (vid_h > HSTX_VID_H_MAX) vid_h = HSTX_VID_H_MAX;
    if (vid_w < 2) vid_w = 2;
    if (vid_h < 1) vid_h = 1;
    vid_w &= ~1;                           // even: two RGB565 px per 32-bit word
    g_region_h = vid_h;                    // stored region height

    const int hborder_l = (MODE_H_ACTIVE_PIXELS - vid_w) / 2;
    const int hborder_r = MODE_H_ACTIVE_PIXELS - vid_w - hborder_l;
    const int vtop = (MODE_V_ACTIVE_LINES - vid_h) / 2;
    const uint32_t border2 = ((uint32_t)BORDER_RGB565 << 16) | BORDER_RGB565;

    unsigned fill = 0;
    emit_vblank_band(&fill, 0, MODE_V_FRONT_PORCH);
    emit_vblank_band(&fill, 1, MODE_V_SYNC_WIDTH);
    emit_vblank_band(&fill, 0, MODE_V_BACK_PORCH);

    g_region_base = NULL;
    for (int y = 0; y < MODE_V_ACTIVE_LINES; y++) {
        framebuf[fill++] = HSTX_CMD_RAW_REPEAT | MODE_H_FRONT_PORCH; framebuf[fill++] = SYNC_V1_H1;
        framebuf[fill++] = HSTX_CMD_RAW_REPEAT | MODE_H_SYNC_WIDTH;  framebuf[fill++] = SYNC_V1_H0;
        framebuf[fill++] = HSTX_CMD_RAW_REPEAT | MODE_H_BACK_PORCH;  framebuf[fill++] = SYNC_V1_H1;
        if (y < vtop || y >= vtop + vid_h) {
            framebuf[fill++] = HSTX_CMD_TMDS_REPEAT | MODE_H_ACTIVE_PIXELS;
            framebuf[fill++] = border2;
        } else {
            framebuf[fill++] = HSTX_CMD_TMDS_REPEAT | hborder_l; framebuf[fill++] = border2;
            framebuf[fill++] = HSTX_CMD_TMDS | vid_w;
            uint16_t *px = (uint16_t *)&framebuf[fill];
            if (!g_region_base) g_region_base = px;
            for (int x = 0; x < vid_w; x++) px[x] = 0x0000;   // video starts black
            fill += (unsigned)vid_w / 2;
            framebuf[fill++] = HSTX_CMD_TMDS_REPEAT | hborder_r; framebuf[fill++] = border2;
        }
    }
    g_fill = fill;
    // Per video line: 11 + vid_w/2 dwords. Stride in uint16 elements:
    g_video_stride = (11 + vid_w / 2) * 2;
}

// One-time HSTX peripheral + pin configuration (encoder, polarity, pads).
static void hstx_setup_peripheral(void) {
    hstx_ctrl_hw->csr = 0;
    hstx_ctrl_hw->csr =
        HSTX_CTRL_CSR_EXPAND_EN_BITS |
        5u << HSTX_CTRL_CSR_CLKDIV_LSB |
        5u << HSTX_CTRL_CSR_N_SHIFTS_LSB |
        2u << HSTX_CTRL_CSR_SHIFT_LSB |
        HSTX_CTRL_CSR_EN_BITS;

    // FreeWili pinout/polarity: clock pair GP12/13 on HSTX bit 0/1 with the ODD
    // gpio (13, _P) NON-inverted and the EVEN gpio (12, _N) INVERTED; data lanes
    // on bit 2/4/6 likewise (odd=_P non-inv, even=_N inv). Matches dvhstx.
    hstx_ctrl_hw->bit[1] = HSTX_CTRL_BIT0_CLK_BITS;                           // GP13 CLK_P
    hstx_ctrl_hw->bit[0] = HSTX_CTRL_BIT0_CLK_BITS | HSTX_CTRL_BIT0_INV_BITS; // GP12 CLK_N
    for (unsigned lane = 0; lane < 3; ++lane) {
        static const int lane_to_output_bit[3] = {2, 4, 6};   // even (_N) gpio bit
        int bit = lane_to_output_bit[lane];
        uint32_t sel = (lane * 10) << HSTX_CTRL_BIT0_SEL_P_LSB |
                       (lane * 10 + 1) << HSTX_CTRL_BIT0_SEL_N_LSB;
        hstx_ctrl_hw->bit[bit + 1] = sel;                            // odd (_P): non-inv
        hstx_ctrl_hw->bit[bit    ] = sel | HSTX_CTRL_BIT0_INV_BITS;  // even (_N): inv
    }

    hstx_ctrl_hw->expand_tmds =
        4  << HSTX_CTRL_EXPAND_TMDS_L2_NBITS_LSB | 8  << HSTX_CTRL_EXPAND_TMDS_L2_ROT_LSB |
        5  << HSTX_CTRL_EXPAND_TMDS_L1_NBITS_LSB | 3  << HSTX_CTRL_EXPAND_TMDS_L1_ROT_LSB |
        4  << HSTX_CTRL_EXPAND_TMDS_L0_NBITS_LSB | 29 << HSTX_CTRL_EXPAND_TMDS_L0_ROT_LSB;
    hstx_ctrl_hw->expand_shift =
        2  << HSTX_CTRL_EXPAND_SHIFT_ENC_N_SHIFTS_LSB |
        16 << HSTX_CTRL_EXPAND_SHIFT_ENC_SHIFT_LSB |
        1  << HSTX_CTRL_EXPAND_SHIFT_RAW_N_SHIFTS_LSB |
        0  << HSTX_CTRL_EXPAND_SHIFT_RAW_SHIFT_LSB;

    for (int g = 12; g <= 19; ++g) gpio_set_function(g, 0);   // GPIO_FUNC_HSTX == 0
}

// (Re)configure and start the SCREEN+LOOPER scanout DMA for the current buffer.
// Zero-IRQ: no DMA_IRQ_0 handler is installed.
static void hstx_dma_start(void) {
    if (ch_screen < 0) ch_screen = dma_claim_unused_channel(true);
    if (ch_looper < 0) ch_looper = dma_claim_unused_channel(true);

    dma_channel_config c;
    c = dma_channel_get_default_config(ch_screen);
    channel_config_set_chain_to(&c, ch_looper);
    channel_config_set_dreq(&c, DREQ_HSTX);
    dma_channel_configure(ch_screen, &c, &hstx_fifo_hw->fifo, framebuf, g_fill, false);

    c = dma_channel_get_default_config(ch_looper);
    channel_config_set_chain_to(&c, ch_screen);
    channel_config_set_dreq(&c, DREQ_HSTX);
    channel_config_set_read_increment(&c, false);
    channel_config_set_write_increment(&c, false);
    dma_channel_configure(ch_looper, &c, &dma_hw->ch[ch_screen].read_addr,
                          &g_loop_src, 1, false);

    dma_channel_start(ch_screen);
}

// ----------------------------------------------------------------------------
// Public API

void hstx_dvi_init(int vid_w, int vid_h) {
    uint32_t fsys = clock_get_hz(clk_sys);
    // clk_hstx = clk_sys / 2 (integer divide; clk_sys must be even MHz). Keeps
    // clk_sys high while clk_hstx -> 25.2 MHz DVI pixel clock.
    clock_configure(clk_hstx, 0, CLOCKS_CLK_HSTX_CTRL_AUXSRC_VALUE_CLK_SYS,
                    fsys, fsys / 2);

    hstx_setup_peripheral();
    hstx_build(HSTX_VID_W_MAX, HSTX_VID_H_MAX);   // fixed region, built ONCE
    hstx_dvi_set_geometry(vid_w, vid_h);          // center the initial movie size
    hstx_dma_start();                             // scanout runs forever on framebuf
}

// Recenter the movie within the FIXED region: clear the region to black (so the
// letterbox margins are black) and point g_video_base at the centered top-left.
// Deliberately does NOT touch the scanout DMA.
void hstx_dvi_set_geometry(int vid_w, int vid_h) {
    if (vid_w > HSTX_VID_W_MAX) vid_w = HSTX_VID_W_MAX;
    if (vid_h > g_region_h) vid_h = g_region_h;
    if (vid_w < 2) vid_w = 2;
    if (vid_h < 1) vid_h = 1;
    vid_w &= ~1;
    g_movie_w = vid_w;
    g_movie_h = vid_h;

    for (int yy = 0; yy < g_region_h; yy++) {
        uint16_t *row = g_region_base + (size_t)yy * g_video_stride;
        for (int xx = 0; xx < HSTX_VID_W_MAX; xx++) row[xx] = 0x0000;
    }
    int off_x = (HSTX_VID_W_MAX - vid_w) / 2;
    int off_y = (g_region_h - vid_h) / 2;
    g_video_base = g_region_base + (size_t)off_y * g_video_stride + off_x;
}

uint16_t *hstx_dvi_video_base(void)  { return g_video_base; }
uint16_t *hstx_dvi_region_base(void) { return g_region_base; }
int       hstx_dvi_video_stride(void) { return g_video_stride; }
int       hstx_dvi_video_w(void)      { return g_movie_w; }
int       hstx_dvi_video_h(void)      { return g_movie_h; }
int       hstx_dvi_region_h(void)     { return g_region_h; }

void hstx_dvi_enable(bool on) {
    // Park the three DATA lanes (GP14-19) low when off; leave the CLK pair
    // (GP12/13) on HSTX so the monitor keeps its pixel-clock lock. Instant, and
    // it never touches the scanout DMA or the framebuffer.
    for (int g = 14; g <= 19; g++) {
        if (on) {
            gpio_set_function(g, 0);   // back to HSTX
        } else {
            gpio_init(g);              // -> SIO
            gpio_set_dir(g, GPIO_OUT);
            gpio_put(g, 0);
        }
    }
}
