// bsp/display/hstx_dvi.h — 640x480p60 DVI over the RP2350 HSTX block (GPIO 12-19).
// Harvested from ../movieplayer (plain-DVI path only; the HDMI-audio-island mode was
// stripped). Architecture (proven by the movie player's Phase-0 spike):
//   - zero-IRQ baked-command DMA (a SCREEN channel streams a command buffer to the
//     HSTX FIFO; a LOOPER channel restarts it) — no interrupts,
//   - framebuffer in SRAM (PSRAM scanout underruns the FIFO and wedges flash),
//   - the <=480x320 video region is stored; the surrounding 640x480 border is
//     GENERATED by the command list (HSTX_CMD_TMDS_REPEAT), not stored,
//   - clk_hstx = clk_sys/2, read at runtime from clk_sys. An exact 25.2 MHz pixel
//     (640x480p60) needs clk_sys = 252 MHz (even); at the 250 MHz board default the
//     pixel is 25.0 MHz (0.7% low). Apps select the clock via board_init_clk().
#ifndef HSTX_DVI_H_
#define HSTX_DVI_H_
#include <stdint.h>
#include <stdbool.h>

// The DVI frame is fixed 640x480p60. The centered video region may be up to
// 480x320; the rest is HSTX-generated border (not stored).
#define HSTX_DVI_W 640
#define HSTX_DVI_H 480
#define HSTX_VID_W_MAX 480
// Max stored DVI video height. 480x320 = the full panel size. The ~327 KB SRAM
// command buffer (see hstx_dvi.c) leaves ample room in a copy_to_ram demo; lower
// this #define if the DVI driver is ever linked alongside the USB/FatFs + LCD-strip
// stack in one binary. Taller frames are center-cropped on DVI.
#define HSTX_VID_H_MAX 320

// Configure clk_hstx (= clk_sys/2), the HSTX block and GPIO 12-19, build the
// scanout command buffer for a vid_w x vid_h video centered in 640x480, and start
// the zero-IRQ baked-command DMA. clk_sys must already be at its final (even MHz)
// value. The video region is cleared to black; it stays valid for program life.
void hstx_dvi_init(int vid_w, int vid_h);

// Rebuild the centered video size (call at content start). vid_w is rounded down to
// even; both dims are clamped to HSTX_VID_*_MAX. Does NOT touch the scanout DMA.
void hstx_dvi_set_geometry(int vid_w, int vid_h);

// The video region as a strided native-endian RGB565 framebuffer: row y of the
// video lives at hstx_dvi_video_base() + y*hstx_dvi_video_stride(), and is
// hstx_dvi_video_w() pixels wide. (Pixels are interleaved with command words,
// hence the stride.) The writer stores pixels native little-endian (NO byte-swap).
uint16_t *hstx_dvi_video_base(void);
// Pixel(0,0) of the FIXED region (the movie is centered within it; the OSD draws
// in the margin below the movie). Same stride as hstx_dvi_video_stride().
uint16_t *hstx_dvi_region_base(void);
int hstx_dvi_video_stride(void);   // uint16 elements between consecutive rows
int hstx_dvi_video_w(void);
int hstx_dvi_video_h(void);
// Height of the FIXED region in rows (HSTX_VID_H_MAX). OSD row math MUST use this.
int hstx_dvi_region_h(void);

// Blank/unblank the three DVI DATA lanes (the CLK lane keeps running so the
// monitor stays locked). Instant; leaves the scanout DMA and framebuffer intact.
void hstx_dvi_enable(bool on);

#endif // HSTX_DVI_H_
